---
title: "Cyberarxiv Dashboard"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(cyberarxiv)
library(dplyr)
library(plotly)
library(lubridate)
```

## Summary of publications

```{r load-data}
if (file.exists('raw-data/arxiv_papers.rds')) {
  data <- cyberarxiv::load_raw_data()
} else {
  data <- cyberarxiv::get_arxiv_papers(max_results = 100)
  cyberarxiv::save_raw_data(data)
}

pubs <- cyberarxiv::classify_data(data)
cyberarxiv::save_publications(pubs)
final <- cyberarxiv::load_publications()
```

### Publications by month

```{r pubs-by-month}
pubs_by_month <- final %>% count(published_date = lubridate::floor_date(published_date, 'month'))
plot_ly(pubs_by_month, x = ~published_date, y = ~n, type = 'scatter', mode = 'lines+markers')
```

### Top authors

```{r top-authors}
authors_long <- final %>%
  select(paper_id, authors) %>%
  tidyr::separate_rows(authors, sep = ",\\s*") %>%
  mutate(authors = trimws(authors))
top_authors <- authors_long %>% count(authors, sort = TRUE) %>% head(10)
plot_ly(top_authors, x = ~reorder(authors, n), y = ~n, type = 'bar')
```
